version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - ./app.env.db
    ports:
      - "55433:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "8088:8088"
      - "9099:9099"
    depends_on:
      - postgres
    entrypoint: 
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]
