version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    networks:
      - bank-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    env_file:
      - ./app.env
    networks:
      - bank-network
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "8088:8088"
      - "9099:9099"
    networks:
      - bank-network
    depends_on:
      - postgres
      - redis
    entrypoint: 
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "redis:6379",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]

networks:
  bank-network:

volumes:
  postgres_data:
  redis_data: