apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::789326847655:user/github-ci
      username: github-ci
      groups:
      - system:masters

